version: 2
jobs:
   build:
     docker:
       - image: circleci/php:7.1-jessie-node
     steps:
       - checkout
       - run: echo "hello world"
   deploy:
       machine:
         enabled: true
       steps:
        - add_ssh_keys:
                  fingerprints:
                    - "de:7e:77:3b:5b:5f:b2:38:95:ab:ed:1f:24:9c:55:3c"
         - run:
             name: Deploy Over SSH
             command: |
               ssh $SSH_USER@$SSH_HOST "cd public_html/circleci && git pull origin master"
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master