version: 2
jobs:
   build:
     docker:
       - image: circleci/php:7.1-jessie-node
     steps:
       - checkout
       - run: echo "hello world"
   deploy:
       machine:
         enabled: true
       steps:
          - add_ssh_keys:
                     fingerprints:
                       - "31:34:98:35:20:70:07:4b:12:4c:37:6b:d2:97:69:1b"
          - run:
             name: Deploy Over SSH
             command: |
               ssh -t $SSH_USER@$SSH_HOST "cd public_html/circleci && git pull origin master"
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:

          requires:
            - build
          filters:
            branches:
              only: master